src/accounts/urls.py
from accounts.views import AccountCreateView, AccountListView, AccountLoginView, AccountLogoutView, \
    AccountPasswordChangeView, AccountUpdateView, ContactView, LeaderboardListView, TrialLessonView


from django.urls import path


app_name = 'accounts'

urlpatterns = [
    path('', AccountListView.as_view(), name='users'),
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='password'),
    path('leaderboard/', LeaderboardListView.as_view(), name='leaderboard'),
    path('contact_us/', ContactView.as_view(), name='contact_us'),
    path('trial_lesson/', TrialLessonView.as_view(), name='trial_lesson'),
    ]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

API_PREFIX = 'api/v1'

urlpatterns = [

    # UI
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('testify/', include('testify.urls')),
    path('main/', include('main.urls')),

    # API
    path(f'{API_PREFIX}/testify/', include('testify.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    ]

handler404 = views.error_404
handler400 = views.error_400
handler403 = views.error_403
handler500 = views.error_500

src/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    # posts
    path("posts", views.PostsListView.as_view(), name="posts"),
    path("make_post", views.PostCreateView.as_view(), name="make_post"),
    path("update_post/<int:pk>", views.PostsUpdateView.as_view(), name="update_post"),
    path("delete_post/<int:pk>", views.PostDeleteView.as_view(), name="delete_post"),

    # lessons
    path("lessons", views.LessonsListView.as_view(), name="lessons"),
    path("lessons_per_month", views.LessonsPerMonthListView.as_view(), name="lessons_per_month"),
    path("create_lesson", views.LessonsCreateView.as_view(), name="create_lesson"),
    path("delete_lesson/<int:pk>", views.LessonsDeleteView.as_view(), name="delete_lesson"),
    path("edit_lesson/<int:pk>", views.LessonsUpdateView.as_view(), name="edit_lesson"),

    # clients
    path("clients", views.ClientCreateView.as_view(), name="clients"),
    path("delete_client/<int:pk>", views.ClientDeleteView.as_view(), name="delete_client"),
    path("edit_client/<int:pk>", views.ClientUpdateView.as_view(), name="edit_client"),

    # other
    path("create_comment/<int:pk>", views.CommentCreateView.as_view(), name="create_comment"),
    path("about", views.about, name="about"),
    path("courses", views.courses, name="courses"),
]

src/testify/urls.py
from django.urls import path

from testify.views import QuestionView, ResultListView, TestDetailView, TestListView, TestRunnerView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('results', ResultListView.as_view(), name='results'),
    path('<int:id>/', TestDetailView.as_view(), name='details'),
    path('<int:id>/start/', TestRunnerView.as_view(), name='start'),
    path('<int:id>/next/', QuestionView.as_view(), name='next'),
]

src/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- XDSoft DateTimePicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>


{% block title%}
    <title>FAST ENGLISH</title>
{% endblock %}
<style type="text/css">

* {
  margin: 0;
  padding: 0;
}

.c {
    font-size: 50%;
    background: #faf0e6; /* Цвет фона */
    border: 1px solid #01796f; /* Рамка */
    border-radius: 15px;
    display: inline-block;
    padding: 5px 15px; /* Поля */
    text-decoration: none; /* Убираем подчёркивание */
    color: #01796f; /* Цвет текста */
}

body {
    height: 100%;
    background: url({% static "common/img/bg1.jpg" %}) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    background-attachment: fixed;
       }
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

.wrapper {
  height: 100%;
}

.content {
  box-sizing: border-box;
  min-height: 100%;
  padding-bottom: 90px;

</style>
</head>

<body>

{%url 'tests:list' as List %}
{%url 'accounts:leaderboard' as Leaderboard %}
{%url 'accounts:users' as Users %}
{%url 'accounts:profile' as Profile %}
{%url 'accounts:register' as Register %}
{%url 'accounts:login' as Login %}

{% if request.user_agent.is_mobile %}

    <div class="container">

            {% if user.is_authenticated %}
                <small>
                        <a href="{% url 'core:index' %}" class="c">FAST ENGLISH</a>

                        <a href="{% url 'tests:list' %}" class="c">Tests</a>

                        <a href="{% url 'tests:results' %}" class="c">My results</a>

                        <a href="{% url 'main:posts' %}" class="c">Posts</a>

                        <a href="{% url 'main:courses' %}" class="c">Courses</a>

                        <a href="{% url 'main:about' %}" class="c">About</a>

                        <a href="{% url 'accounts:trial_lesson' %}" class="c">Trial lesson</a>

                        <a href="{% url 'accounts:contact_us' %}" class="c">Contact us</a>

                        <a href="{% url 'accounts:logout' %}" class="c">Log out</a>

                        <a href="{% url 'accounts:profile' %}" class="c">Profile ({{ user.username }})</a>


                    {% else %}

                        <a href="{% url 'main:posts' %}" class="c">Posts</a>

                        <a href="{% url 'main:courses' %}" class="c">Courses</a>

                        <a href="{% url 'main:about' %}" class="c">About</a>

                        <a href="{% url 'accounts:trial_lesson' %}" class="c">Trial lesson</a>

                        <a href="{% url 'accounts:contact_us' %}" class="c">Contact us</a>

                        <a href="{% url 'accounts:register' %}" class="c">Register</a>

                        <a href="{% url 'accounts:login' %}" class="c">Login</a>


                    {% endif %}

                    {% if user.is_superuser %}

                        <a href="{% url 'accounts:leaderboard' %}" class="c">Leaderboard</a>

                        <a href="{% url 'accounts:users' %}" class="c">Users</a>

                        <a href="{% url 'main:lessons' %}" class="c">lessons</a>

                        <a href="{% url 'main:clients' %}" class="c">clients</a>

                        <a href="{% url 'admin:index' %}" class="c">admin</a>
                </small>
            {% endif %}
    </div>

{% else %}

<nav class="navbar navbar-expand-lg navbar-primary bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">FAST ENGLISH</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link" href=#">Test<span class="sr-only">(current)</span></a>-->
<!--          </li>-->
<!--            <li class="nav-item active">-->
<!--            <a class="nav-link" href=#>Test<span class="sr-only">(current)</span></a>-->
<!--          </li>-->
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link" href=#">Test</a>-->
<!--          </li>-->
    <!--      <li class="nav-item dropdown">-->
    <!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
    <!--          Dropdown-->
    <!--        </a>-->
    <!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
    <!--          <a class="dropdown-item" href="#">Action</a>-->
    <!--          <a class="dropdown-item" href="#">Another action</a>-->
    <!--          <div class="dropdown-divider"></div>-->
    <!--          <a class="dropdown-item" href="#">Something else here</a>-->
    <!--        </div>-->
    <!--      </li>-->
    <!--      <li class="nav-item">-->
    <!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
    <!--      </li>-->
        </ul>
    <!--    <form class="form-inline my-2 my-lg-0">-->
    <!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
    <!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    <!--    </form>-->
            <ul class="navbar-nav">

                {% if user.is_authenticated %}

                <li class="nav-item {% if request.path == List %} active {% endif %}">
                    <a class="nav-link" href="{% url 'tests:list' %}">Tests</a>
                </li>

                <li class="nav-item {% if request.path == List %} active {% endif %}">
                    <a class="nav-link" href="{% url 'tests:results' %}">My results</a>
                </li>

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:posts' %}">Posts</a>
                </li>

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:courses' %}">Courses</a>
                </li>

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:about' %}">About</a>
                </li>

<!--                <li class="nav-item {% if request.path == Leaderboard %} active {% endif %}">-->
<!--                    <a class="nav-link" href="{% url 'accounts:leaderboard' %}">Leaderboard</a>-->
<!--                </li>-->
<!--                <li class="nav-item {% if request.path == Users %} active {% endif %}">-->
<!--                    <a class="nav-link" href="{% url 'accounts:users' %}">Users</a>-->
<!--                </li>-->

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:trial_lesson' %}">Trial lesson</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:contact_us' %}">Contact us</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                </li>

                <li class="img-circle.vert">
                    <img class="rounded-circle p-1 m-1" width="40" height="40" src=" {{ user.image.url }} ">
                </li>

                <li class="nav-item {% if request.path == Profile %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>

                {% else %}

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:posts' %}">Posts</a>
                </li>

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:courses' %}">Courses</a>
                </li>

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'main:about' %}">About</a>
                </li>

<!--                <li class="nav-item {% if request.path == Leaderboard %} active {% endif %}">-->
<!--                    <a class="nav-link" href="{% url 'accounts:leaderboard' %}">Leaderboard</a>-->
<!--                </li>-->
<!--                <li class="nav-item {% if request.path == Users %} active {% endif %}">-->
<!--                    <a class="nav-link" href="{% url 'accounts:users' %}">Users</a>-->
<!--                </li>-->

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:trial_lesson' %}">Trial lesson</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:contact_us' %}">Contact us</a>
                </li>

                <li class="nav-item {% if request.path == Register %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>


                {% endif %}

                {% if user.is_superuser %}

                <li>
                    <a class="nav-link" href="{% url 'main:lessons' %}">lessons</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'main:clients' %}">clients</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'admin:index' %}">admin</a>
                </li>

                {% endif %}

            </ul>
      </div>
    </div>
</nav>

{% endif %}

{% include 'includes/messages.html' %}

<div class="wrapper">

    <div class="content">

        <div class="container">
            <div class="border border-white rounded-pill shadow p-3 mb-5 mt-5 bg-white rounded text-center">
                {% block header %}
                {% endblock %}
            </div>
            {% block video %}
            {% endblock %}

            {% block content %}
            {% endblock %}

        </div><br>

    </div>

</div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}


    {% block video %}
        <div class="banner">
        <link rel="stylesheet" href="{% static 'common/img/style.css' %}">
        <video src="{% static 'common/img/Letters.mp4' %}" autoplay muted loop></video>
            <div id="fast_english" class="content" style="width: 1000px; height: 1000px;">
                <h2 style="margin: 0; padding: 0; font-size: 6em; text-transform: uppercase; ">Fast English</h2><br>
            </div>
        </div>
    {% endblock %}


<!--    <form>-->
<!--        <input formaction="{% url 'accounts:leaderboard' %}" type="submit" class="btn btn-info" value="Leaderboard">-->
<!--    </form><br>-->

<!--    <form>-->
<!--        <input formaction="{% url 'tests:list' %}" type="submit" class="btn btn-primary btn-lg btn-block" value="Tests">-->
<!--    </form><br>-->

<!--    <form>-->
<!--        <input formaction="{% url 'tests:results' %}" type="submit" class="btn btn-secondary btn-lg btn-block" value="My results">-->
<!--    </form><br>-->

<!--    <form>-->
<!--        <input formaction="{% url 'accounts:users' %}" type="submit" class="btn btn-info" value="Users">-->
<!--    </form>-->