src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

API_PREFIX = 'api/v1'

urlpatterns = [

    # UI
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('testify/', include('testify.urls')),
    path('main/', include('main.urls')),

    # API
    path(f'{API_PREFIX}/testify/', include('testify.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    # posts
    path("posts", views.PostsListView.as_view(), name="posts"),
    path("make_post", views.PostCreateView.as_view(), name="make_post"),
    path("update_post/<int:pk>", views.PostsUpdateView.as_view(), name="update_post"),
    path("delete_post/<int:pk>", views.PostDeleteView.as_view(), name="delete_post"),

    # lessons
    path("lessons", views.LessonsListView.as_view(), name="lessons"),
    path("lessons_per_month", views.LessonsPerMonthListView.as_view(), name="lessons_per_month"),
    path("create_lesson", views.LessonsCreateView.as_view(), name="create_lesson"),
    path("delete_lesson/<int:pk>", views.LessonsDeleteView.as_view(), name="delete_lesson"),
    path("edit_lesson/<int:pk>", views.LessonsUpdateView.as_view(), name="edit_lesson"),

    # clients
    path("clients", views.ClientCreateView.as_view(), name="clients"),
    path("delete_client/<int:pk>", views.ClientDeleteView.as_view(), name="delete_client"),
    path("edit_client/<int:pk>", views.ClientUpdateView.as_view(), name="edit_client"),

    # other
    path("create_comment/<int:pk>", views.CommentCreateView.as_view(), name="create_comment"),
    path("about", views.about, name="about"),
    path("courses", views.courses, name="courses"),
]

src/main/models.py
from datetime import datetime, timedelta

from accounts.models import User

from core.models import BaseModel
from core.utils import resize_image_for_post

from django.db import models


class Post(BaseModel):
    title = models.CharField("Название", max_length=128)
    content = models.TextField("Контент")
    image = models.ImageField(upload_to='pics/', default='pics/fi1.jpg')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        result = super().save(*args, **kwargs)
        resize_image_for_post(self.image)
        return result

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["-create_date"]


class Comment(BaseModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.TextField("Комментарий", max_length=256)
    comment_date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return self.comment_text

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ["create_date"]


class Level(models.Model):
    level = models.CharField("Уровень", max_length=8)

    def __str__(self):
        return self.level

    class Meta:
        verbose_name = "Уровень"
        verbose_name_plural = "Уровни"


class Client(BaseModel):
    firstname = models.CharField("Имя", max_length=64)
    lastname = models.CharField("Фамилия", max_length=64)
    phone = models.CharField("Телефон", max_length=24)
    email = models.EmailField("Почта", max_length=48)
    age = models.SmallIntegerField("Возраст", null=True)
    skype = models.CharField("Skype", max_length=124, null=True)
    level = models.ForeignKey(to=Level, on_delete=models.CASCADE)
    teacher = models.ForeignKey(
        to=User, null=False, blank=False, default=11, on_delete=models.SET_DEFAULT, related_name='clients'
    )

    def __str__(self):
        return self.firstname

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Lessons(BaseModel):
    teacher = models.ForeignKey(
        to=User, null=False, blank=False, default=11, on_delete=models.SET_DEFAULT, related_name='lessons'
    )
    client = models.ForeignKey(
        to=Client, null=False, blank=False, default=11, on_delete=models.SET_DEFAULT, related_name='lessons'
    )
    date = models.DateTimeField("Дата", null=True, blank=True)
    price = models.IntegerField("Цена")
    was = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Занятие"
        verbose_name_plural = "Занятия"
        ordering = ["date"]

    def __str__(self):
        return str(self.client)

    @classmethod
    def get_this_month_income(cls, *args):
        current_month = datetime.now().month
        current_year = datetime.now().year
        if args:
            this_month_lessons = cls.objects.filter(date__month=current_month, date__year=current_year, teacher=args[0])
        else:
            this_month_lessons = cls.objects.filter(date__month=current_month, date__year=current_year)
        month_income = 0
        for lesson in this_month_lessons:
            month_income += lesson.price
        return month_income

    @classmethod
    def get_this_day_income(cls, *args):
        current_day = datetime.now().day
        current_month = datetime.now().month
        current_year = datetime.now().year
        if args:
            this_day_income = cls.objects.filter(date__month=current_month, date__year=current_year,
                                                 date__day=current_day, teacher=args[0])
        else:
            this_day_income = cls.objects.filter(date__month=current_month, date__year=current_year,
                                                 date__day=current_day)
        today_income = 0
        for lesson in this_day_income:
            today_income += lesson.price
        return today_income

    @classmethod
    def get_this_week_lessons(cls, user):
        days = [
            (1, 'sunday'), (2, 'monday'), (3, 'tuesday'), (4, 'wednesday'),
            (5, 'thursday'), (6, 'friday'), (7, 'saturday')
        ]
        querysets = []
        for day, day_of_week in days:
            one_day_lessons = cls.objects.filter(teacher=user,
                                                 date__week_day=day, date__gte=(datetime.now() - timedelta(days=1)),
                                                 date__lte=(datetime.now() + timedelta(days=6))).order_by("date")
            item = {
                'index': day,
                'lessons': one_day_lessons,
                'day_of_week': day_of_week,
            }
            querysets.append(item)
        return querysets

src/main/forms.py
from accounts.models import User

from django import forms
from django.forms import ModelForm, TextInput, Textarea

from .models import Client, Comment, Lessons, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "image"]
        widgets = {
            "title": TextInput(
                attrs={"class": "form-control", "placeholder": "Введите название"}
            ),
            "content": Textarea(
                attrs={"class": "form-control", "placeholder": "Введите описание"}
            ),
        }


class CommentForm(ModelForm):

    comment_text = forms.CharField(
        label="Ваш комментарий",
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control", "placeholder": "Введите комментарий"}
        ),
    )

    class Meta:
        model = Comment
        fields = ["comment_text"]


class ClientForm(ModelForm):
    teacher = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=True))

    class Meta:
        model = Client
        fields = [
            "firstname",
            "lastname",
            "phone",
            "email",
            "age",
            "skype",
            "level",
            "teacher",
        ]
        widgets = {
            "firstname": TextInput(
                attrs={"class": "form-control", "placeholder": "Введите имя"}
            ),
            "lastname": TextInput(
                attrs={"class": "form-control", "placeholder": "Введите фамилию"}
            ),
            "age": TextInput(
                attrs={"class": "form-control", "placeholder": "Введите возраст"}
            ),
            "skype": TextInput(
                attrs={"class": "form-control", "placeholder": "Введите скайп"}
            ),
            "phone": TextInput(
                attrs={"class": "form-control", "placeholder": "Введите телефон"}
            ),
            "email": TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите адрес электронной почты",
                }
            ),
        }


class LessonsForm(ModelForm):
    date = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"])
    teacher = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=True))

    class Meta:
        model = Lessons
        fields = ["client", "teacher", "date", "price", "was"]

src/main/views.py
from datetime import datetime, timedelta

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import ClientForm, CommentForm, LessonsForm, PostForm
from .models import Client, Comment, Lessons, Post


class SuperUserCheckMixin(UserPassesTestMixin, View):
    """mixin for checking superuser"""
    def test_func(self):
        return self.request.user.is_superuser


class PostCreateView(SuperUserCheckMixin, CreateView):
    """create posts and show them"""
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("main:posts")
    template_name = "make_post.html"

    def get_context_data(self, **kwargs):
        kwargs["posts"] = Post.objects.all()
        return super().get_context_data(**kwargs)


class PostsListView(ListView):
    """show all posts and comment to them"""
    model = Post
    form_class = CommentForm
    success_url = reverse_lazy("main:posts")
    template_name = "posts_list.html"

    def get_context_data(self, **kwargs):
        kwargs["posts"] = Post.objects.all()
        kwargs["comments"] = Comment.objects.all()
        return super().get_context_data(**kwargs)


class PostsUpdateView(SuperUserCheckMixin, UpdateView):
    """post editing"""
    model = Post
    template_name = "update_post.html"
    context_object_name = "post"
    form_class = PostForm
    success_url = reverse_lazy("main:posts")


class PostDeleteView(SuperUserCheckMixin, DeleteView):
    """delete post"""
    model = Post
    template_name = "delete_post.html"
    success_url = reverse_lazy("main:make_post")


class CommentCreateView(LoginRequiredMixin, CreateView):
    """create a comment on the selected post"""
    model = Comment
    form_class = CommentForm
    success_url = reverse_lazy("main:posts")
    template_name = "detail_post.html"

    def get_context_data(self, **kwargs):
        kwargs["post"] = Post.objects.get(id=self.kwargs["pk"])
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        post = Post.objects.get(id=self.kwargs["pk"])
        user = self.request.user
        form = form.save(commit=False)
        form.post = post
        form.user = user
        form.save()
        context = {
            'posts': Post.objects.all(),
            'comments': Comment.objects.all()
        }
        return render(self.request, 'posts_list.html', context)


class ClientCreateView(SuperUserCheckMixin, CreateView, ListView):
    """create a new client"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("main:clients")
    template_name = "clients.html"
    paginate_by = 20
    context_object_name = "clients"


class ClientUpdateView(SuperUserCheckMixin, UpdateView):
    """update client data"""
    model = Client
    template_name = "edit_client.html"
    context_object_name = "clients"
    form_class = ClientForm
    success_url = reverse_lazy("main:clients")


class ClientDeleteView(SuperUserCheckMixin, DeleteView):
    """delete client"""
    model = Client
    template_name = "delete_client.html"
    success_url = reverse_lazy("main:clients")


class LessonsCreateView(SuperUserCheckMixin, CreateView):
    """create a lesson"""
    model = Lessons
    form_class = LessonsForm
    success_url = reverse_lazy("main:lessons")
    template_name = "create_lesson.html"


class LessonsListView(SuperUserCheckMixin, ListView):
    """show lessons by filters"""
    model = Lessons
    success_url = reverse_lazy("main:lessons")
    template_name = "lessons.html"
    paginate_by = 20
    context_object_name = "this_month_lessons"

    def get_context_data(self, **kwargs):
        kwargs['this_day_income'] = Lessons.get_this_day_income(self.request.user)
        kwargs['this_day_income_all_teachers'] = Lessons.get_this_day_income()
        kwargs['this_week_lessons'] = sorted(Lessons.get_this_week_lessons(self.request.user), key=lambda k: k['index'])
        kwargs['this_month_income'] = Lessons.get_this_month_income(self.request.user)
        kwargs['this_month_income_all_teachers'] = Lessons.get_this_month_income()
        kwargs["sum_this_month_lessons"] = len(Lessons.objects.filter(
            date__gte=datetime(datetime.today().year, datetime.today().month, 1), teacher=self.request.user)
        )
        kwargs["sum_this_month_lessons_all_teachers"] = len(Lessons.objects.filter(
            date__gte=datetime(datetime.today().year, datetime.today().month, 1))
        )
        kwargs['today_lessons'] = Lessons.objects.filter(date__date=datetime.today(), teacher=self.request.user)
        kwargs['tomorrow_lessons'] = Lessons.objects.filter(
            date__date=datetime.today() + timedelta(days=1), teacher=self.request.user
        )
        kwargs["sum_today_lessons"] = len(kwargs['today_lessons'])
        return super().get_context_data(**kwargs)


class LessonsPerMonthListView(SuperUserCheckMixin, ListView):
    """show lessons per month (for the current month)"""
    model = Lessons
    template_name = "lessons_per_month.html"
    paginate_by = 20
    context_object_name = "this_month_lessons"

    def get_queryset(self):
        lessons = super().get_queryset()
        today = datetime.today()
        datem = datetime(today.year, today.month, 1)
        this_month_lessons = lessons.filter(date__gte=datem, teacher=self.request.user).order_by("date")
        return this_month_lessons

    def get_context_data(self, **kwargs):
        kwargs['this_month_income'] = Lessons.get_this_month_income(self.request.user)
        kwargs['this_month_income_all_teachers'] = Lessons.get_this_month_income()
        kwargs['this_day_income'] = Lessons.get_this_day_income(self.request.user)
        kwargs['this_day_income_all_teachers'] = Lessons.get_this_day_income()
        kwargs["sum_this_month_lessons"] = len(self.get_queryset())
        kwargs["sum_this_month_lessons_all_teachers"] = len(
            Lessons.objects.filter(date__gte=datetime(datetime.today().year, datetime.today().month, 1))
        )
        return super().get_context_data(**kwargs)


class LessonsUpdateView(SuperUserCheckMixin, UpdateView):
    """edit lesson"""
    model = Lessons
    template_name = "edit_lesson.html"
    form_class = LessonsForm
    success_url = reverse_lazy("main:lessons")


class LessonsDeleteView(SuperUserCheckMixin, DeleteView):
    """delete lesson"""
    model = Lessons
    template_name = "delete_lesson.html"
    success_url = reverse_lazy("main:lessons")


def about(request):
    """about information"""
    return render(request, "about.html")


def courses(request):
    """courses information"""
    return render(request, "courses.html")

src/main/templates/clients.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    <title>Клиенты</title>
{% endblock %}

{% block header%}
    <h3>Clients</h3>
{% endblock %}

{% block content %}

    <div class="alert alert-warning mt-1">
        <h3>Клиенты:</h3><br>
        <table border="1" width="100%" cellpadding="5">
            <tr>
                <td><strong>Имя</strong></td>
                <td><strong>Фамилия</strong></td>
                <td><strong>Телефон</strong></td>
                <td><strong>Почта</strong></td>
                <td><strong>Возраст</strong></td>
                <td><strong>Скайп</strong></td>
                <td><strong>Уровень</strong></td>
                <td><strong>Преподаватель</strong></td>
                <td><strong>Редактировать данные</strong></td>
                <td><strong>Удалить ученика</strong></td>
            <tr>
            {% for client in clients %}
            <tr>
                <td>{{ client.firstname }}</td>
                <td>{{ client.lastname }}</td>
                <td>{{ client.phone }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.age }}</td>
                <td>{{ client.skype }}</td>
                <td>{{ client.level }}</td>
                <td>{{ client.teacher }}</td>
                <td>
                    <form action="{% url 'main:edit_client' client.id %}">{% csrf_token %}
                        <button class="btn btn-info">Редактировать данные</button>
                    </form>
                    <br>
                </td>
                <td>
                    <form action="{% url 'main:delete_client' client.id %}">{% csrf_token %}
                        <button class="btn btn-warning">Удалить ученика</button>
                    </form>
                    <br>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <form method="post">
    {% csrf_token %}
        <div class="alert alert-warning mt-4">
            <h3>Добавить нового клиента</h3><br>
                {{ form|crispy }}<br>
            <button type="submit" class="btn btn-success">Добавить ученика</button><br>
            <br>
        </div>
    </form>

    <div class="p-1 m-1">
        {% include 'includes/pagination.html' %}
    </div>

{% endblock %}

src/main/templates/create_lesson.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
    <title>Занятия</title>
{% endblock %}

{% block header%}
    <h3>Lessons</h3>
{% endblock %}

{% block content %}

    <div class="alert alert-warning mt-4">
        <h3>Добавить новое занятие</h3><br>
            <form method="post">
            {% csrf_token %}
                <h4>Выберите клиента:</h4>
                {{ form.client }}<br>
                <br>
                <h4>Выберите преподавателя:</h4>
                {{ form.teacher }}<br>
                <br>
                <h4>Дата и время занятия:</h4>
                {{ form.date }}
                    <script>
                        $(function () {
                        $("#id_date").datetimepicker({
                        format: 'd/m/Y H:i',
                        });
                        });
                    </script><br>
                <br>
                <h4>Цена:</h4>
                {{ form.price }}<br>
                <br>
                <h4>Было ли занятие:</h4>
                {{ form.was }}<br>
                <br>
                    <button type="submit" class="btn btn-success">Добавить урок</button><br>
                    <br>
            </form>
    </div>

{% endblock %}

src/main/templates/lessons.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
    <title>Занятия</title>
{% endblock %}

{% block header%}
    <h3>Lessons</h3>
{% endblock %}

{% block content %}

    <div>
        <form action="{% url 'main:create_lesson' %}">
            <button class="btn btn-primary btn-lg btn-block">Добавить урок</button> {% csrf_token %}
        </form>
    </div>
    <br>
    <div>
        <form action="{% url 'main:lessons_per_month' %}">
            <button class="btn btn-info btn-lg btn-block">Все занятия за месяц</button> {% csrf_token %}
        </form>
    </div>
    <br>

    <div class="alert alert-warning mt-1">
        <h3>Занятия сегодня:</h3><br>
        <table border="1" width="100%" cellpadding="5">
            <tr>
                <td><strong>Клиент</strong></td>
                <td><strong>Преподаватель</strong></td>
                <td><strong>Дата и время</strong></td>
                <td><strong>Цена</strong></td>
                <td><strong>Было ли занятие</strong></td>
                <td><strong>Редактировать</strong></td>
                <td><strong>Удалить занятие</strong></td>
            <tr>
            {% for lesson in today_lessons %}
            <tr>
                <td>{{ lesson.client }}</td>
                <td>{{ lesson.teacher.full_name }}</td>
                <td>{{ lesson.date }}</td>
                <td>{{ lesson.price }}</td>
                <td>{{ lesson.whose }}</td>
                <td>{{ lesson.was }}</td>
                <td>
                    <form action="{% url 'main:edit_lesson' lesson.id %}">
                        <button class="btn btn-info">Редактировать урок</button> {% csrf_token %}
                    </form>
                    <br>
                </td>
                <td>
                    <form action="{% url 'main:delete_lesson' lesson.id %}">
                        <button class="btn btn-warning">Удалить урок</button> {% csrf_token %}
                    </form>
                    <br>
                </td>
            </tr>
            {% endfor %}
        </table><br>
    </div>

    <div class="alert alert-warning mt-1">
        <h3>Занятия завтра:</h3><br>
        <table border="1" width="100%" cellpadding="5">
            <tr>
                <td><strong>Клиент</strong></td>
                <td><strong>Преподаватель</strong></td>
                <td><strong>Дата и время</strong></td>
                <td><strong>Цена</strong></td>
                <td><strong>Было ли занятие</strong></td>
                <td><strong>Редактировать</strong></td>
                <td><strong>Удалить занятие</strong></td>
            <tr>
            {% for lesson in tomorrow_lessons %}
            <tr>
                <td>{{ lesson.client }}</td>
                <td>{{ lesson.teacher.full_name }}</td>
                <td>{{ lesson.date }}</td>
                <td>{{ lesson.price }}</td>
                <td>{{ lesson.was }}</td>
                <td>
                    <form action="{% url 'main:edit_lesson' lesson.id %}">
                        <button class="btn btn-info">Редактировать урок</button> {% csrf_token %}
                    </form>
                    <br>
                </td>
                <td>
                    <form action="{% url 'main:delete_lesson' lesson.id %}">
                        <button class="btn btn-warning">Удалить урок</button> {% csrf_token %}
                    </form>
                    <br>
                </td>
            </tr>
            {% endfor %}
        </table><br>
    </div>

<h3>Занятия на неделю:</h3><br>

{% for item in this_week_lessons %}
    <div class="alert alert-warning mt-1">
        <h3>{{item.day_of_week}}</h3><br>
            <table border="1" width="100%" cellpadding="5">
                <tr>
                    <td><strong>Клиент</strong></td>
                    <td><strong>Преподаватель</strong></td>
                    <td><strong>Дата и время</strong></td>
                    <td><strong>Цена</strong></td>
                    <td><strong>Было ли занятие</strong></td>
                    <td><strong>Редактировать</strong></td>
                    <td><strong>Удалить занятие</strong></td>
                <tr>
                {% for lesson in item.lessons %}
                <tr>
                    <td>{{ lesson.client }}</td>
                    <td>{{ lesson.teacher.full_name }}</td>
                    <td>{{ lesson.date }}</td>
                    <td>{{ lesson.price }}</td>
                    <td>{{ lesson.was }}</td>
                    <td>
                        <form action="{% url 'main:edit_lesson' lesson.id %}">
                            <button class="btn btn-info">Редактировать урок</button> {% csrf_token %}
                        </form>
                        <br>
                    </td>
                    <td>
                        <form action="{% url 'main:delete_lesson' lesson.id %}">
                            <button class="btn btn-warning">Удалить урок</button> {% csrf_token %}
                        </form>
                        <br>
                    </td>
                </tr>
                {% endfor %}
            </table><br><br>
    </div>

{% endfor %}


    <div>
        <table border="1" width="100%" cellpadding="5">
            <tr>
                <td><p>Занятий в этом месяце:</p></td>
                <td>{{ sum_this_month_lessons }}</td>
            </tr>
            <tr>
                <td><p>Доход за месяц:</p></td>
                <td>{{ this_month_income }}</td>
            </tr>
            <tr>
                <td><p>Доход за сегодня:</p></td>
                <td>{{ this_day_income }}</td>
            </tr>
            <tr>
                <td><p>Занятий у всех преподавателей в этом месяце:</p></td>
                <td>{{ sum_this_month_lessons_all_teachers }}</td>
            </tr>
            <tr>
                <td><p>Доход всех преподавателей за месяц :</p></td>
                <td>{{ this_month_income_all_teachers }}</td>
            </tr>
            <tr>
                <td><p>Доход всех преподавателей за сегодня:</p></td>
                <td>{{ this_day_income_all_teachers }}</td>
            </tr>
        </table>
    </div>

{% endblock %}

src/main/templates/lessons_per_month.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
    <title>Занятия</title>
{% endblock %}

{% block header%}
    <h3>Lessons</h3>
{% endblock %}

{% block content %}

    <div class="alert alert-warning mt-1">
        <h3>Все занятия:</h3><br>
        <table border="1" width="100%" cellpadding="5">
            <tr>
                <td><strong>Клиент</strong></td>
                <td><strong>Преподаватель</strong></td>
                <td><strong>Дата и время</strong></td>
                <td><strong>Цена</strong></td>
                <td><strong>Было ли занятие</strong></td>
                <td><strong>Редактировать</strong></td>
                <td><strong>Удалить занятие</strong></td>
            <tr>
            {% for lesson in this_month_lessons %}
            <tr>
                <td>{{ lesson.client }}</td>
                <td>{{ lesson.teacher.full_name }}</td>
                <td>{{ lesson.date }}</td>
                <td>{{ lesson.price }}</td>
                <td>{{ lesson.was }}</td>
                <td>
                    <form action="{% url 'main:edit_lesson' lesson.id %}">
                        <button class="btn btn-info">Редактировать урок</button> {% csrf_token %}
                    </form>
                    <br>
                </td>
                <td>
                    <form action="{% url 'main:delete_lesson' lesson.id %}">
                        <button class="btn btn-warning">Удалить урок</button> {% csrf_token %}
                    </form>
                    <br>
                </td>
            </tr>
            {% endfor %}
        </table><br>
        <table border="1" width="100%" cellpadding="5">
            <tr>
                <td><p>Занятий в этом месяце:</p></td>
                <td>{{ sum_this_month_lessons }}</td>
            </tr>
            <tr>
                <td><p>Доход за месяц:</p></td>
                <td>{{ this_month_income }}</td>
            </tr>
            <tr>
                <td><p>Доход за сегодня:</p></td>
                <td>{{ this_day_income }}</td>
            </tr>
            <tr>
                <td><p>Занятий у всех преподавателей в этом месяце:</p></td>
                <td>{{ sum_this_month_lessons_all_teachers }}</td>
            </tr>
            <tr>
                <td><p>Доход всех преподавателей за месяц :</p></td>
                <td>{{ this_month_income_all_teachers }}</td>
            </tr>
            <tr>
                <td><p>Доход всех преподавателей за сегодня:</p></td>
                <td>{{ this_day_income_all_teachers }}</td>
            </tr>
        </table>
    </div>

    <br>
        <p style="text-align: center"><a href="{% url 'main:lessons' %}">Вернуться назад</a></p>
    <br>

    <div class="p-1 m-1">
        {% include 'includes/pagination.html' %}
    </div>

{% endblock %}

src/main/templates/make_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Создать статью</title>
{% endblock %}

{% block header%}
    <h3>Make post</h3>
{% endblock %}

{% block content %}
    <div class="container" style="text-align: center">
        <h1>Создать статью</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-success">Добавить</button><br>
            <br>
        </form><br>
    </div>

    <div class="container" style="text-align: center">
        <h1>Статьи:</h1><br>
        {% for post in posts %}
            <div class="alert alert-warning mt-4">
                <h2>{{post.title}}</h2><br>
                <h4>{{post.content|truncatechars:"300"}}</h4><br>
                    <img width="600" height="500" src=" {{ post.image.url }} "><br><br>

                <form action="{% url 'main:create_comment' post.id %}">
                    <button class="btn btn-success">Перейти к статье</button> {% csrf_token %}
                </form><br>

                <form action="{% url 'main:update_post' post.id %}">
                    <button class="btn btn-primary">Редактировать статью</button> {% csrf_token %}
                </form><br>

                <form action="{% url 'main:delete_post' post.id %}">
                    <button class="btn btn-warning">Удалить статью</button> {% csrf_token %}
                </form>
            </div>
        {% endfor %}
    </div>
{% endblock %}

